package nl.sander.beejava;

public enum Opcode {
    LOAD("load"),
    STORE("store"),
    CONST("const"),
    NEWARRAY("new"),
    RETURN("return"),
    ARRAYLENGTH("length"),
    THROW("throw"),
    PUSH("push"),
    CHECKCAST("checkcast"),
    ADD("add"),
    COMPARE("cmp"),
    DIVIDE("div"),
    MULTIPLY("mul"),
    NEGATE("neg"),
    REMAINDER("rem"),
    SUBTRACT("sub"),
    DUPLICATE("dup"),
    DUPLICATE_DOWN("dup_x1"),
    DUPLICATE2("dup2"),
    DUPLICATE2_DOWN("dup2_x1"),
    GET("get"),
    GOTO("goto"),
    GOTO_W("goto_w"),
    TO_DOUBLE("2d"),
    TO_INT("2i"),
    TO_LONG("2l"),
    TO_BYTE("2b"),
    TO_CHAR("2c"),
    TO_FLOAT("2f"),
    TO_SHORT("2s"),
    AND("and"),
    IF_EQUAL("ifeq"),
    IF_NOT_EQUAL("ifneq"),
    IF_LESS_THAN("iflt"),
    IF_GREATER_OR_EQUAL("ifge"),
    IF_GREATER_THAN("ifgt"),
    IF_LESS_OR_EQUAL("ifle"),
    IF_NOT_NULL("ifnotnull"),
    IF_NULL("ifnull"),
    INCREMENT("inc"),
    INSTANCEOF("instanceof"),
    INVOKE("invoke"),
    OR("or"),
    SHIFT_LEFT("shr"),
    SHIFT_RIGHT("shl"),
    LOGICAL_SHIFT_RIGHT("ushr"),
    XOR("xor"),
    LOOKUPSWITCH("lookupswitch"),
    MONITORENTER("monitorenter"),
    MONITOREXIT("monitorexit"),
    MULTIANEWARRAY("multinewarray"),
    NEW("new"),
    NOP("nop"),
    POP("pop"),
    POP2("pop2"),
    PUT("put"),
    SWAP("swap"),
    TABLESWITCH("tableswitch"),
    WIDE("wide");

    private final String name;

    Opcode(String name) {
        this.name=name;
    }
}
